#:schema node_modules/wrangler/config-schema.json
name = "icloud-private-relay-ip-list-manager"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

# Environment variables
[vars]
#API_TOKEN = "ABCD" # Replace with your Cloudflare API token, preferably use Secrets. Permission "Account Filter Lists" needed!
#ACCOUNT_ID = "ABCD" # Replace with your Cloudflare account ID
LIST_NAME = "icloud_private_relay_egress_ips" # Replace with your desired list name
IPV4_LIST_SOURCE_URL = "https://raw.githubusercontent.com/hroost/icloud-private-relay-iplist/refs/heads/main/ipv4/ipv4-ranges.json"
IPV6_LIST_SOURCE_URL = "https://raw.githubusercontent.com/hroost/icloud-private-relay-iplist/refs/heads/main/ipv6/ipv6-ranges.json"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Cron trigger configuration
[triggers]
crons = ["0 0 */14 * *"]
